DELETE FROM t_BTS_Assignees;
DELETE FROM t_BTS_Bugs;
DELETE FROM t_BTS_Notes;
DELETE FROM t_BTS_Tags;
DELETE FROM t_BTS_TagTypes;
DELETE FROM t_Organisations;
DELETE FROM t_OrgMembers;
DELETE FROM t_Users;